---
title: "Acerca de mí"
---


Mi nombre es Manuel Toral, actualmente trabajo con datos judiciales para el análisis de política pública, fui investigador especializado en datos en Mexicanos Contra la Corrupción y la Impunidad. Estudié Política Pública en la *Harris School of Public Policy* en la Universidad de Chicago y Ciencia Política y Relaciones Internacionales en el Centro de Investigación y Docencia Económicas. Como instructor en R, soy parte del directorio de instructores de RStudio.

Llevo 6 años usando R de manera profesional en una diversidad de proyectos de temas inmobiliarios, geográficos, análisis de grandes cantidades de datos, seguridad, corrupción, transparencia y combate a la impunidad en México. Puedes ver algo de mis últimos trabajos de investigación con datos en el blog Desarmando la Corrupción de *MCCI* en alianza con la revista Nexos o en el Taller de Datos de la misma publicación.

Como docente en R, he sido el experto residente de la *Harris School of Public Policy* en la Universidad de Chicago, en la que dirigí la *STATA and R Bar*, que asesoraba en el uso de estas herramientas a alumnos de maestría y doctorado. En 2017, fui contratado por la Unidad de Investigación Aplicada de *MCCI* para capacitar a sus integrantes en el uso de R, equipo al que finalmente me integré como investigador. He dado cerca de 50 cursos y capacitado a poco más de 500 personas en el uso del lenguaje R, además de haber impartido capacitaciones al personal docente del Sistema Tecnológico de Monterrey.
