---
title: "Syllabus"
subtitle: <h4 style="font-style:normal">Curso introductorio al lenguaje R</h4>
date: <h4 style="font-style:normal">Febrero/Marzo 2021</h4>
output: 
  html_document:
    toc: true
    toc_depth: 3
    toc_float: true
    theme: cosmo
---


<style>
p.comment {
background-color: #DBDBDB;
padding: 10px;
border: 1px solid black;
margin-left: 25px;
border-radius: 5px;
font-style: italic;
}

.figure {
   margin-top: 20px;
   margin-bottom: 20px;
}

h1.title {
  font-weight: bold;
  font-family: Arial;  
}

h2.title {
  font-family: Arial;  
}

</style>


<style type="text/css">
#TOC {
  font-size: 13px;
  font-family: Arial;
}
</style>

\

## Sesión 1

### Visualizaciones avanzadas

- Veremos algunas visualizaciones interactivas y profundizaremos más sobre el trabajo de la gramática de gráficos.
- Haremos gráficas interactivas.
- Animaremos algunas animaciones.

<div style="margin-bottom:25px;">
</div>


### Scraping básico y análisis de lenguaje natural

- Con base en las mañaneras del Presidente de la República y de `rvest` vamos a descargar información de la web y analizarla.


<div style="margin-bottom:25px;">
</div>

### Trabajo de encuestas y uso de directorios

<div style="margin-bottom:25px;">
</div>



### Una provocación a los modelos de predicción

<div style="margin-bottom:25px;">
</div>


